paths:
  legendary_path:
    duration-seconds: 6.0
    smoothing: "catmull-rom"
    constant-speed: true
    step-resolution: 0.12
    points:
      - { x: 0, y: 2, z: -4, yaw: 0, pitch: -10 }
      - { x: 1.5, y: 2.2, z: -2, yaw: 10, pitch: -5 }
      - { x: 0.5, y: 1.8, z: 0.5, yaw: 0, pitch: 0 }
      - { x: -0.5, y: 1.6, z: 2.5, yaw: -30, pitch: 10 }
    direct-points: [2]
    start-commands:
      - "say %player% inicio la ruta legendary_path"
    player-segments:
      - start-point: 1
        end-point: 3
    particle-preview: "end_rod"
  seasonal_line:
    duration-seconds: 4.0
    smoothing: "linear"
    constant-speed: true
    step-resolution: 0.16
    points:
      - { x: 0, y: 1.6, z: -3, yaw: 0, pitch: 0 }
      - { x: 0, y: 1.6, z: 0, yaw: 0, pitch: 0 }
    particle-preview: "happy_villager"
